version: '3.4'

services:   

  maria:
    build:
        context: ./mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_psw1
      MYSQL_DATABASE: db1
      MYSQL_USER: user1
      MYSQL_PASSWORD: psw1
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: